from .states import *
from .orders import *

HOLD_NO_POSITION = (NO_POSITION, HOLD_POSITION)

START_LONG_POSITION = (NO_POSITION, OPEN_LONG_POSITION)
HOLD_LONG_POSITION = (LONG_POSITION, HOLD_POSITION)
END_LONG_POSITION = (LONG_POSITION, END_POSITION)

START_SHORT_POSITION = (NO_POSITION, OPEN_SHORT_POSITION)
HOLD_SHORT_POSITION = (SHORT_POSITION, HOLD_POSITION)
END_SHORT_POSITION = (SHORT_POSITION, END_POSITION)

FROM_SHORT_TO_LONG_POSITION = (SHORT_POSITION, OPEN_LONG_POSITION)
FROM_LONG_TO_SHORT_POSITION = (LONG_POSITION, OPEN_SHORT_POSITION)